title:  iOS Development
name: Nitrogen 
user_description: Former ACM ICPC 2017 Asia-Manila Competitive Programmer
user_description_1: Programmer | (Interested in Clean Code) 🌱
notes_url: "https://github.com/nitrogen17"
profile_pic: /assets/img/profile-icon.jpg
favicon: /assets/img/favicon.png
copyright_name: nitrogen17
baseurl: "/" # the subpath of your site, e.g. /blog
url: "www.nitrodev.ga" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

disqus:
  shortname: raghuveerdotnet

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
